name: CI Unit Tests

on:
  push:
    branches: [ main, copilot/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # Install playwright if requirements.txt doesn't exist
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install playwright
          fi

      - name: Run Unit Tests
        run: |
          pytest -q tests/test_fingerprint_utils.py
